<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE articles [<!ELEMENT articles ANY><!ELEMENT article ANY><!ATTLIST article id ID #REQUIRED>]>
<articles folder="c:\content" type="ApiReference" version="16.2" docsdir="api-reference">
  <article name="UI Widgets" sort="10 UI Widgets" id="UI Widgets" root="true" file="c:\content\10 UI Widgets\10 UI Widgets.md">
    <article name="dxAccordion" sort="dxAccordion" id="UI Widgets/dxAccordion" root="true" css="c:\content\10 UI Widgets\dxAccordion\dxAccordion.css" html="c:\content\10 UI Widgets\dxAccordion\dxAccordion.html" js="c:\content\10 UI Widgets\dxAccordion\dxAccordion.js" file="c:\content\10 UI Widgets\dxAccordion\dxAccordion.md">
      <article name="Configuration" sort="1 Configuration" id="UI Widgets/dxAccordion/Configuration" root="true" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\Configuration.md">
        <article name="accessKey" sort="accessKey" id="UI Widgets/dxAccordion/Configuration/accessKey" file="c:\content\10 UI Widgets\Widget\1 Configuration\accessKey.md" />
        <article name="activeStateEnabled" sort="activeStateEnabled" id="UI Widgets/dxAccordion/Configuration/activeStateEnabled" file="c:\content\10 UI Widgets\Widget\1 Configuration\activeStateEnabled.md" />
        <article name="animationDuration" sort="animationDuration" id="UI Widgets/dxAccordion/Configuration/animationDuration" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\animationDuration.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\animationDuration.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\animationDuration.js" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\animationDuration.md" />
        <article name="collapsible" sort="collapsible" id="UI Widgets/dxAccordion/Configuration/collapsible" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\collapsible.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\collapsible.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\collapsible.js" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\collapsible.md" />
        <article name="dataSource" sort="dataSource" id="UI Widgets/dxAccordion/Configuration/dataSource" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\dataSource.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\dataSource.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\dataSource.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\dataSource.md" />
        <article name="deferRendering" sort="deferRendering" id="UI Widgets/dxAccordion/Configuration/deferRendering" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\deferRendering.md" />
        <article name="disabled" sort="disabled" id="UI Widgets/dxAccordion/Configuration/disabled" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\disabled.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\disabled.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\disabled.js" file="c:\content\10 UI Widgets\Widget\1 Configuration\disabled.md" />
        <article name="elementAttr" sort="elementAttr" id="UI Widgets/dxAccordion/Configuration/elementAttr" file="c:\content\10 UI Widgets\DOMComponent\1 Configuration\elementAttr.md" />
        <article name="focusStateEnabled" sort="focusStateEnabled" id="UI Widgets/dxAccordion/Configuration/focusStateEnabled" file="c:\content\10 UI Widgets\Widget\1 Configuration\focusStateEnabled.md;c:\content\10 UI Widgets\dxAccordion\1 Configuration\focusStateEnabled.md" />
        <article name="height" sort="height" id="UI Widgets/dxAccordion/Configuration/height" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\height.md" />
        <article name="hint" sort="hint" id="UI Widgets/dxAccordion/Configuration/hint" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\hint.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\hint.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\hint.js" file="c:\content\10 UI Widgets\Widget\1 Configuration\hint.md" />
        <article name="hoverStateEnabled" sort="hoverStateEnabled" id="UI Widgets/dxAccordion/Configuration/hoverStateEnabled" file="c:\content\10 UI Widgets\Widget\1 Configuration\hoverStateEnabled.md;c:\content\10 UI Widgets\dxAccordion\1 Configuration\hoverStateEnabled.md" />
        <article name="itemHoldTimeout" sort="itemHoldTimeout" id="UI Widgets/dxAccordion/Configuration/itemHoldTimeout" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\itemHoldTimeout.md" />
        <article name="items" sort="items" id="UI Widgets/dxAccordion/Configuration/items" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\items.md" array="true" />
        <article name="itemTemplate" sort="itemTemplate" id="UI Widgets/dxAccordion/Configuration/itemTemplate" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTemplate.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTemplate.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTemplate.js" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTemplate.md" />
        <article name="itemTitleTemplate" sort="itemTitleTemplate" id="UI Widgets/dxAccordion/Configuration/itemTitleTemplate" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTitleTemplate.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTitleTemplate.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTitleTemplate.js" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\itemTitleTemplate.md" />
        <article name="keyExpr" sort="keyExpr" id="UI Widgets/dxAccordion/Configuration/keyExpr" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\keyExpr.md" />
        <article name="multiple" sort="multiple" id="UI Widgets/dxAccordion/Configuration/multiple" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\multiple.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\multiple.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\multiple.js" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\multiple.md" />
        <article name="noDataText" sort="noDataText" id="UI Widgets/dxAccordion/Configuration/noDataText" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\noDataText.md" />
        <article name="onContentReady" sort="onContentReady" id="UI Widgets/dxAccordion/Configuration/onContentReady" file="c:\content\10 UI Widgets\Widget\1 Configuration\onContentReady.md;c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onContentReady.md" />
        <article name="onDisposing" sort="onDisposing" id="UI Widgets/dxAccordion/Configuration/onDisposing" file="c:\content\10 UI Widgets\Component\1 Configuration\onDisposing.md;c:\content\10 UI Widgets\DOMComponent\1 Configuration\onDisposing.md" />
        <article name="onInitialized" sort="onInitialized" id="UI Widgets/dxAccordion/Configuration/onInitialized" file="c:\content\10 UI Widgets\Component\1 Configuration\onInitialized.md" />
        <article name="onItemClick" sort="onItemClick" id="UI Widgets/dxAccordion/Configuration/onItemClick" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemClick.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemClick.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemClick.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemClick.md" />
        <article name="onItemContextMenu" sort="onItemContextMenu" id="UI Widgets/dxAccordion/Configuration/onItemContextMenu" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemContextMenu.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemContextMenu.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemContextMenu.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemContextMenu.md" />
        <article name="onItemHold" sort="onItemHold" id="UI Widgets/dxAccordion/Configuration/onItemHold" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemHold.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemHold.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemHold.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemHold.md" />
        <article name="onItemRendered" sort="onItemRendered" id="UI Widgets/dxAccordion/Configuration/onItemRendered" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemRendered.md" />
        <article name="onItemTitleClick" sort="onItemTitleClick" id="UI Widgets/dxAccordion/Configuration/onItemTitleClick" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemTitleClick.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemTitleClick.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemTitleClick.js" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onItemTitleClick.md" />
        <article name="onOptionChanged" sort="onOptionChanged" id="UI Widgets/dxAccordion/Configuration/onOptionChanged" file="c:\content\10 UI Widgets\Component\1 Configuration\onOptionChanged.md;c:\content\10 UI Widgets\DOMComponent\1 Configuration\onOptionChanged.md" />
        <article name="onSelectionChanged" sort="onSelectionChanged" id="UI Widgets/dxAccordion/Configuration/onSelectionChanged" css="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onSelectionChanged.css" html="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onSelectionChanged.html" js="c:\content\10 UI Widgets\dxAccordion\1 Configuration\onSelectionChanged.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onSelectionChanged.md" />
        <article name="rtlEnabled" sort="rtlEnabled" id="UI Widgets/dxAccordion/Configuration/rtlEnabled" file="c:\content\10 UI Widgets\DOMComponent\1 Configuration\rtlEnabled.md" />
        <article name="selectedIndex" sort="selectedIndex" id="UI Widgets/dxAccordion/Configuration/selectedIndex" file="c:\content\10 UI Widgets\dxAccordion\1 Configuration\selectedIndex.md" />
        <article name="selectedItem" sort="selectedItem" id="UI Widgets/dxAccordion/Configuration/selectedItem" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\selectedItem.md" />
        <article name="selectedItemKeys" sort="selectedItemKeys" id="UI Widgets/dxAccordion/Configuration/selectedItemKeys" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\selectedItemKeys.md" array="true" />
        <article name="selectedItems" sort="selectedItems" id="UI Widgets/dxAccordion/Configuration/selectedItems" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\selectedItems.md" array="true" />
        <article name="tabIndex" sort="tabIndex" id="UI Widgets/dxAccordion/Configuration/tabIndex" file="c:\content\10 UI Widgets\Widget\1 Configuration\tabIndex.md" />
        <article name="visible" sort="visible" id="UI Widgets/dxAccordion/Configuration/visible" file="c:\content\10 UI Widgets\Widget\1 Configuration\visible.md" />
        <article name="width" sort="width" id="UI Widgets/dxAccordion/Configuration/width" file="c:\content\10 UI Widgets\DOMComponent\1 Configuration\width.md" />
      </article>
      <article name="Methods" sort="3 Methods" id="UI Widgets/dxAccordion/Methods" root="true" file="c:\content\10 UI Widgets\dxAccordion\3 Methods\Methods.md">
        <article name="beginUpdate()" sort="beginUpdate()" id="UI Widgets/dxAccordion/Methods/beginUpdate()" file="c:\content\10 UI Widgets\Component\3 Methods\beginUpdate().md" />
        <article name="collapseItem(index)" sort="collapseItem(index)" id="UI Widgets/dxAccordion/Methods/collapseItem(index)" file="c:\content\10 UI Widgets\dxAccordion\3 Methods\collapseItem(index).md" />
        <article name="defaultOptions(rule)" sort="defaultOptions(rule)" id="UI Widgets/dxAccordion/Methods/defaultOptions(rule)" file="c:\content\10 UI Widgets\DOMComponent\3 Methods\defaultOptions(rule).md" />
        <article name="element()" sort="element()" id="UI Widgets/dxAccordion/Methods/element()" file="c:\content\10 UI Widgets\DOMComponent\3 Methods\element().md" />
        <article name="endUpdate()" sort="endUpdate()" id="UI Widgets/dxAccordion/Methods/endUpdate()" file="c:\content\10 UI Widgets\Component\3 Methods\endUpdate().md" />
        <article name="expandItem(index)" sort="expandItem(index)" id="UI Widgets/dxAccordion/Methods/expandItem(index)" file="c:\content\10 UI Widgets\dxAccordion\3 Methods\expandItem(index).md" />
        <article name="focus()" sort="focus()" id="UI Widgets/dxAccordion/Methods/focus()" file="c:\content\10 UI Widgets\Widget\3 Methods\focus().md" />
        <article name="getDataSource()" sort="getDataSource()" id="UI Widgets/dxAccordion/Methods/getDataSource()" file="c:\content\10 UI Widgets\DataHelperMixin\3 Methods\getDataSource().md" />
        <article name="instance()" sort="instance()" id="UI Widgets/dxAccordion/Methods/instance()" file="c:\content\10 UI Widgets\Component\3 Methods\instance().md" />
        <article name="off(eventName)" sort="off(eventName)" id="UI Widgets/dxAccordion/Methods/off(eventName)" file="c:\content\10 UI Widgets\EventsMixin\3 Methods\off(eventName).md" />
        <article name="off(eventName, eventHandler)" sort="off(eventName, eventHandler)" id="UI Widgets/dxAccordion/Methods/off(eventName_eventHandler)" file="c:\content\10 UI Widgets\EventsMixin\3 Methods\off(eventName_eventHandler).md" />
        <article name="on(eventName, eventHandler)" sort="on(eventName, eventHandler)" id="UI Widgets/dxAccordion/Methods/on(eventName_eventHandler)" file="c:\content\10 UI Widgets\EventsMixin\3 Methods\on(eventName_eventHandler).md" />
        <article name="on(events)" sort="on(events)" id="UI Widgets/dxAccordion/Methods/on(events)" file="c:\content\10 UI Widgets\EventsMixin\3 Methods\on(events).md" />
        <article name="option()" sort="option()" id="UI Widgets/dxAccordion/Methods/option()" file="c:\content\10 UI Widgets\Component\3 Methods\option().md" />
        <article name="option(optionName)" sort="option(optionName)" id="UI Widgets/dxAccordion/Methods/option(optionName)" file="c:\content\10 UI Widgets\Component\3 Methods\option(optionName).md" />
        <article name="option(optionName, optionValue)" sort="option(optionName, optionValue)" id="UI Widgets/dxAccordion/Methods/option(optionName_optionValue)" file="c:\content\10 UI Widgets\Component\3 Methods\option(optionName_optionValue).md" />
        <article name="option(options)" sort="option(options)" id="UI Widgets/dxAccordion/Methods/option(options)" file="c:\content\10 UI Widgets\Component\3 Methods\option(options).md" />
        <article name="registerKeyHandler(key, handler)" sort="registerKeyHandler(key, handler)" id="UI Widgets/dxAccordion/Methods/registerKeyHandler(key_handler)" file="c:\content\10 UI Widgets\Widget\3 Methods\registerKeyHandler(key_handler).md" />
        <article name="repaint()" sort="repaint()" id="UI Widgets/dxAccordion/Methods/repaint()" file="c:\content\10 UI Widgets\Widget\3 Methods\repaint().md" />
        <article name="updateDimensions()" sort="updateDimensions()" id="UI Widgets/dxAccordion/Methods/updateDimensions()" file="c:\content\10 UI Widgets\dxAccordion\3 Methods\updateDimensions().md" />
      </article>
      <article name="Events" sort="4 Events" id="UI Widgets/dxAccordion/Events" root="true" file="c:\content\10 UI Widgets\dxAccordion\4 Events\Events.md">
        <article name="contentReady" sort="contentReady" id="UI Widgets/dxAccordion/Events/contentReady" file="c:\content\10 UI Widgets\Widget\4 Events\contentReady.md;c:\content\10 UI Widgets\CollectionWidget\4 Events\contentReady.md" />
        <article name="disposing" sort="disposing" id="UI Widgets/dxAccordion/Events/disposing" file="c:\content\10 UI Widgets\Component\4 Events\disposing.md;c:\content\10 UI Widgets\DOMComponent\4 Events\disposing.md" />
        <article name="initialized" sort="initialized" id="UI Widgets/dxAccordion/Events/initialized" file="c:\content\10 UI Widgets\Component\4 Events\initialized.md" />
        <article name="itemClick" sort="itemClick" id="UI Widgets/dxAccordion/Events/itemClick" css="c:\content\10 UI Widgets\dxAccordion\4 Events\itemClick.css" html="c:\content\10 UI Widgets\dxAccordion\4 Events\itemClick.html" js="c:\content\10 UI Widgets\dxAccordion\4 Events\itemClick.js" file="c:\content\10 UI Widgets\CollectionWidget\4 Events\itemClick.md" />
        <article name="itemContextMenu" sort="itemContextMenu" id="UI Widgets/dxAccordion/Events/itemContextMenu" file="c:\content\10 UI Widgets\CollectionWidget\4 Events\itemContextMenu.md" />
        <article name="itemHold" sort="itemHold" id="UI Widgets/dxAccordion/Events/itemHold" file="c:\content\10 UI Widgets\CollectionWidget\4 Events\itemHold.md" />
        <article name="itemRendered" sort="itemRendered" id="UI Widgets/dxAccordion/Events/itemRendered" file="c:\content\10 UI Widgets\CollectionWidget\4 Events\itemRendered.md" />
        <article name="itemTitleClick" sort="itemTitleClick" id="UI Widgets/dxAccordion/Events/itemTitleClick" css="c:\content\10 UI Widgets\dxAccordion\4 Events\itemTitleClick.css" html="c:\content\10 UI Widgets\dxAccordion\4 Events\itemTitleClick.html" js="c:\content\10 UI Widgets\dxAccordion\4 Events\itemTitleClick.js" file="c:\content\10 UI Widgets\dxAccordion\4 Events\itemTitleClick.md" />
        <article name="optionChanged" sort="optionChanged" id="UI Widgets/dxAccordion/Events/optionChanged" file="c:\content\10 UI Widgets\Component\4 Events\optionChanged.md;c:\content\10 UI Widgets\DOMComponent\4 Events\optionChanged.md" />
        <article name="selectionChanged" sort="selectionChanged" id="UI Widgets/dxAccordion/Events/selectionChanged" css="c:\content\10 UI Widgets\dxAccordion\4 Events\selectionChanged.css" html="c:\content\10 UI Widgets\dxAccordion\4 Events\selectionChanged.html" js="c:\content\10 UI Widgets\dxAccordion\4 Events\selectionChanged.js" file="c:\content\10 UI Widgets\CollectionWidget\4 Events\selectionChanged.md" />
      </article>
      <article name="Default Item Template" sort="5 Default Item Template" id="UI Widgets/dxAccordion/Default Item Template" root="true" file="c:\content\10 UI Widgets\dxAccordion\5 Default Item Template\Default Item Template.md">
        <article name="disabled" sort="disabled" id="UI Widgets/dxAccordion/Default Item Template/disabled" file="c:\content\10 UI Widgets\CollectionWidget\5 Default Item Template\disabled.md" />
        <article name="html" sort="html" id="UI Widgets/dxAccordion/Default Item Template/html" file="c:\content\10 UI Widgets\CollectionWidget\5 Default Item Template\html.md" />
        <article name="icon" sort="icon" id="UI Widgets/dxAccordion/Default Item Template/icon" file="c:\content\10 UI Widgets\dxAccordion\5 Default Item Template\icon.md" />
        <article name="iconSrc" sort="iconSrc" id="UI Widgets/dxAccordion/Default Item Template/iconSrc" file="c:\content\10 UI Widgets\dxAccordion\5 Default Item Template\iconSrc.md" deprecated="true" />
        <article name="template" sort="template" id="UI Widgets/dxAccordion/Default Item Template/template" file="c:\content\10 UI Widgets\CollectionWidget\5 Default Item Template\template.md" />
        <article name="text" sort="text" id="UI Widgets/dxAccordion/Default Item Template/text" file="c:\content\10 UI Widgets\CollectionWidget\5 Default Item Template\text.md" />
        <article name="title" sort="title" id="UI Widgets/dxAccordion/Default Item Template/title" file="c:\content\10 UI Widgets\dxAccordion\5 Default Item Template\title.md" />
        <article name="visible" sort="visible" id="UI Widgets/dxAccordion/Default Item Template/visible" file="c:\content\10 UI Widgets\CollectionWidget\5 Default Item Template\visible.md" />
      </article>
    </article>
    <article name="dxActionSheet" sort="dxActionSheet" id="UI Widgets/dxActionSheet" root="true" css="c:\content\10 UI Widgets\dxActionSheet\dxActionSheet.css" html="c:\content\10 UI Widgets\dxActionSheet\dxActionSheet.html" js="c:\content\10 UI Widgets\dxActionSheet\dxActionSheet.js" file="c:\content\10 UI Widgets\dxActionSheet\dxActionSheet.md">
      <article name="Configuration" sort="1 Configuration" id="UI Widgets/dxActionSheet/Configuration" root="true" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\Configuration.md">
        <article name="cancelText" sort="cancelText" id="UI Widgets/dxActionSheet/Configuration/cancelText" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\cancelText.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\cancelText.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\cancelText.js" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\cancelText.md" />
        <article name="dataSource" sort="dataSource" id="UI Widgets/dxActionSheet/Configuration/dataSource" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\dataSource.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\dataSource.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\dataSource.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\dataSource.md" />
        <article name="disabled" sort="disabled" id="UI Widgets/dxActionSheet/Configuration/disabled" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\disabled.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\disabled.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\disabled.js" file="c:\content\10 UI Widgets\Widget\1 Configuration\disabled.md" />
        <article name="elementAttr" sort="elementAttr" id="UI Widgets/dxActionSheet/Configuration/elementAttr" file="c:\content\10 UI Widgets\DOMComponent\1 Configuration\elementAttr.md" />
        <article name="height" sort="height" id="UI Widgets/dxActionSheet/Configuration/height" file="c:\content\10 UI Widgets\DOMComponent\1 Configuration\height.md" />
        <article name="hint" sort="hint" id="UI Widgets/dxActionSheet/Configuration/hint" file="c:\content\10 UI Widgets\Widget\1 Configuration\hint.md" />
        <article name="hoverStateEnabled" sort="hoverStateEnabled" id="UI Widgets/dxActionSheet/Configuration/hoverStateEnabled" file="c:\content\10 UI Widgets\Widget\1 Configuration\hoverStateEnabled.md" />
        <article name="itemHoldTimeout" sort="itemHoldTimeout" id="UI Widgets/dxActionSheet/Configuration/itemHoldTimeout" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\itemHoldTimeout.md" />
        <article name="items" sort="items" id="UI Widgets/dxActionSheet/Configuration/items" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\items.md" array="true" />
        <article name="itemTemplate" sort="itemTemplate" id="UI Widgets/dxActionSheet/Configuration/itemTemplate" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\itemTemplate.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\itemTemplate.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\itemTemplate.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\itemTemplate.md" />
        <article name="onCancelClick" sort="onCancelClick" id="UI Widgets/dxActionSheet/Configuration/onCancelClick" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onCancelClick.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onCancelClick.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onCancelClick.js" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onCancelClick.md" />
        <article name="onContentReady" sort="onContentReady" id="UI Widgets/dxActionSheet/Configuration/onContentReady" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onContentReady.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onContentReady.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onContentReady.js" file="c:\content\10 UI Widgets\Widget\1 Configuration\onContentReady.md;c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onContentReady.md" />
        <article name="onDisposing" sort="onDisposing" id="UI Widgets/dxActionSheet/Configuration/onDisposing" file="c:\content\10 UI Widgets\Component\1 Configuration\onDisposing.md;c:\content\10 UI Widgets\DOMComponent\1 Configuration\onDisposing.md" />
        <article name="onInitialized" sort="onInitialized" id="UI Widgets/dxActionSheet/Configuration/onInitialized" file="c:\content\10 UI Widgets\Component\1 Configuration\onInitialized.md" />
        <article name="onItemClick" sort="onItemClick" id="UI Widgets/dxActionSheet/Configuration/onItemClick" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onItemClick.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onItemClick.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\onItemClick.js" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemClick.md" />
        <article name="onItemContextMenu" sort="onItemContextMenu" id="UI Widgets/dxActionSheet/Configuration/onItemContextMenu" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemContextMenu.md" />
        <article name="onItemHold" sort="onItemHold" id="UI Widgets/dxActionSheet/Configuration/onItemHold" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemHold.md" />
        <article name="onItemRendered" sort="onItemRendered" id="UI Widgets/dxActionSheet/Configuration/onItemRendered" file="c:\content\10 UI Widgets\CollectionWidget\1 Configuration\onItemRendered.md" />
        <article name="onOptionChanged" sort="onOptionChanged" id="UI Widgets/dxActionSheet/Configuration/onOptionChanged" file="c:\content\10 UI Widgets\Component\1 Configuration\onOptionChanged.md;c:\content\10 UI Widgets\DOMComponent\1 Configuration\onOptionChanged.md" />
        <article name="rtlEnabled" sort="rtlEnabled" id="UI Widgets/dxActionSheet/Configuration/rtlEnabled" file="c:\content\10 UI Widgets\DOMComponent\1 Configuration\rtlEnabled.md" />
        <article name="showCancelButton" sort="showCancelButton" id="UI Widgets/dxActionSheet/Configuration/showCancelButton" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showCancelButton.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showCancelButton.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showCancelButton.js" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showCancelButton.md" />
        <article name="showTitle" sort="showTitle" id="UI Widgets/dxActionSheet/Configuration/showTitle" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showTitle.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showTitle.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showTitle.js" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\showTitle.md" />
        <article name="target" sort="target" id="UI Widgets/dxActionSheet/Configuration/target" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\target.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\target.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\target.js" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\target.md" />
        <article name="title" sort="title" id="UI Widgets/dxActionSheet/Configuration/title" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\title.md" />
        <article name="usePopover" sort="usePopover" id="UI Widgets/dxActionSheet/Configuration/usePopover" css="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\usePopover.css" html="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\usePopover.html" js="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\usePopover.js" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\usePopover.md" />
        <article name="visible" sort="visible" id="UI Widgets/dxActionSheet/Configuration/visible" file="c:\content\10 UI Widgets\dxActionSheet\1 Configuration\visible.md" />
        <article name="width" sort="width" id="UI Widgets/dxActionSheet/Configuration/width" file="c:\content\10 UI Widgets\DOMComponent\1 Configuration\width.md" />
      </article>
      <article name="Methods" sort="3 Methods" id="UI Widgets/dxActionSheet/Methods" root="true" file="c:\content\10 UI Widgets\dxActionSheet\3 Methods\Methods.md">
        <article name="beginUpdate()" sort="beginUpdate()" id="UI Widgets/dxActionSheet/Methods/beginUpdate()" file="c:\content\10 UI Widgets\Component\3 Methods\beginUpdate().md" />
        <article name="defaultOptions(rule)" sort="defaultOptions(rule)" id="UI Widgets/dxActionSheet/Methods/defaultOptions(rule)" file="c:\content\10 UI Widgets\DOMComponent\3 Methods\defaultOptions(rule).md" />
        <article name="element()" sort="element()" id="UI Widgets/dxActionSheet/Methods/element()" file="c:\content\10 UI Widgets\DOMComponent\3 Methods\element().md" />
        <article name="endUpdate()" sort="endUpdate()" id="UI Widgets/dxActionSheet/Methods/endUpdate()" file="c:\content\10 UI Widgets\Component\3 Methods\endUpdate().md" />
        <article name="getDataSource()" sort="getDataSource()" id="UI Widgets/dxActionSheet/Methods/getDataSource()" file="c:\content\10 UI Widgets\DataHelperMixin\3 Methods\getDataSource().md" />
        <article name="hide()" sort="hide()" id="UI Widgets/dxActionSheet/Methods/hide()" file="c:\content\10 UI Widgets\dxActionSheet\3 Methods\hide().md" />
        <article name="instance()" sort="instance()" id="UI Widgets/dxActionSheet/Methods/instance()" file="c:\content\10 UI Widgets\Component\3 Methods\instance().md" />