<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE articles [<!ELEMENT articles ANY><!ELEMENT article ANY><!ATTLIST article id ID #REQUIRED>]>
<articles folder="c:\content" type="Howto" version="19.2" docsdir="concepts">
  <article name="Getting Started" sort="00 Getting Started" id="Getting Started">
    <article name="Installation" sort="01 Installation" id="Getting Started/Installation">
      <article name="npm Package" sort="01 npm Package" id="Getting Started/Installation/npm Package" file="c:\content\00 Getting Started\01 Installation\01 npm Package\01 npm Package.md" root="true">
        <article name="Using Yarn" sort="10 Using Yarn" id="Getting Started/Installation/npm Package/Using Yarn" file="c:\content\00 Getting Started\01 Installation\01 npm Package\10 Using Yarn.md" />
      </article>
      <article name="CDN Services" sort="05 CDN Services" id="Getting Started/Installation/CDN Services" file="c:\content\00 Getting Started\01 Installation\05 CDN Services\05 CDN Services.md" root="true">
        <article name="Subresource Integrity Hashes" sort="10 Subresource Integrity Hashes" id="Getting Started/Installation/CDN Services/Subresource Integrity Hashes" file="c:\content\00 Getting Started\01 Installation\05 CDN Services\10 Subresource Integrity Hashes.md" />
      </article>
      <article name="Local Scripts" sort="10 Local Scripts" id="Getting Started/Installation/Local Scripts" file="c:\content\00 Getting Started\01 Installation\10 Local Scripts.md" root="true" />
      <article name="NuGet Package" sort="10 NuGet Package" id="Getting Started/Installation/NuGet Package" file="c:\content\00 Getting Started\01 Installation\10 NuGet Package.md" tags="getting started,install,nuget,package" root="true" />
    </article>
    <article name="Widget Basics - jQuery" sort="10 Widget Basics - jQuery" id="Getting Started/Widget Basics - jQuery">
      <article name="Create and Configure a Widget" sort="01 Create and Configure a Widget" id="Getting Started/Widget Basics - jQuery/Create and Configure a Widget" file="c:\content\00 Getting Started\10 Widget Basics - jQuery\01 Create and Configure a Widget.md" tags="basics,jquery,create,configure,initialize,design time" root="true" />
      <article name="Get a Widget Instance" sort="03 Get a Widget Instance" id="Getting Started/Widget Basics - jQuery/Get a Widget Instance" file="c:\content\00 Getting Started\10 Widget Basics - jQuery\03 Get a Widget Instance.md" root="true" />
      <article name="Get and Set Options" sort="05 Get and Set Options" id="Getting Started/Widget Basics - jQuery/Get and Set Options" file="c:\content\00 Getting Started\10 Widget Basics - jQuery\05 Get and Set Options.md" tags="basics,jquery,change options,get,set,runtime" root="true" />
      <article name="Call Methods" sort="10 Call Methods" id="Getting Started/Widget Basics - jQuery/Call Methods" file="c:\content\00 Getting Started\10 Widget Basics - jQuery\10 Call Methods.md" tags="basics,jquery,call methods,widget instance,method arguments" root="true" />
      <article name="Handle Events" sort="15 Handle Events" id="Getting Started/Widget Basics - jQuery/Handle Events" file="c:\content\00 Getting Started\10 Widget Basics - jQuery\15 Handle Events.md" tags="basics,jquery,handle events,subscribe,unsubscribe,on,off" root="true" />
      <article name="Destroy a Widget" sort="20 Destroy a Widget" id="Getting Started/Widget Basics - jQuery/Destroy a Widget" file="c:\content\00 Getting Started\10 Widget Basics - jQuery\20 Destroy a Widget.md" root="true" />
    </article>
    <article name="Widget Basics - AngularJS" sort="20 Widget Basics - AngularJS" id="Getting Started/Widget Basics - AngularJS">
      <article name="Create and Configure a Widget" sort="01 Create and Configure a Widget" id="Getting Started/Widget Basics - AngularJS/Create and Configure a Widget" file="c:\content\00 Getting Started\20 Widget Basics - AngularJS\01 Create and Configure a Widget.md" tags="basics,angularjs,create,configure,initialize,design time,scope properties" root="true" />
      <article name="Get a Widget Instance" sort="03 Get a Widget Instance" id="Getting Started/Widget Basics - AngularJS/Get a Widget Instance" file="c:\content\00 Getting Started\20 Widget Basics - AngularJS\03 Get a Widget Instance.md" root="true" />
      <article name="Change Options" sort="05 Change Options" id="Getting Started/Widget Basics - AngularJS/Change Options" file="c:\content\00 Getting Started\20 Widget Basics - AngularJS\05 Change Options.md" tags="basics,angularjs,change options,get,set,runtime,binding options,deep tracking,watch,watchCollection,two-way binding" root="true" />
      <article name="Call Methods" sort="10 Call Methods" id="Getting Started/Widget Basics - AngularJS/Call Methods" file="c:\content\00 Getting Started\20 Widget Basics - AngularJS\10 Call Methods.md" tags="basics,angularjs,call methods,widget instance" root="true" />
      <article name="Handle Events" sort="15 Handle Events" id="Getting Started/Widget Basics - AngularJS/Handle Events" file="c:\content\00 Getting Started\20 Widget Basics - AngularJS\15 Handle Events.md" tags="basics,angularjs,handle events,subscribe" root="true" />
      <article name="Destroy a Widget" sort="20 Destroy a Widget" id="Getting Started/Widget Basics - AngularJS/Destroy a Widget" file="c:\content\00 Getting Started\20 Widget Basics - AngularJS\20 Destroy a Widget.md" root="true" />
    </article>
    <article name="Widget Basics - Knockout" sort="25 Widget Basics - Knockout" id="Getting Started/Widget Basics - Knockout">
      <article name="Create and Configure a Widget" sort="01 Create and Configure a Widget" id="Getting Started/Widget Basics - Knockout/Create and Configure a Widget" file="c:\content\00 Getting Started\25 Widget Basics - Knockout\01 Create and Configure a Widget.md" tags="basics,knockout,create,configure,initialize,design time,view model" root="true" />
      <article name="Get a Widget Instance" sort="03 Get a Widget Instance" id="Getting Started/Widget Basics - Knockout/Get a Widget Instance" file="c:\content\00 Getting Started\25 Widget Basics - Knockout\03 Get a Widget Instance.md" root="true" />
      <article name="Change Options" sort="05 Change Options" id="Getting Started/Widget Basics - Knockout/Change Options" file="c:\content\00 Getting Started\25 Widget Basics - Knockout\05 Change Options.md" tags="basics,knockout,change options,get,set,runtime,observables,two-way binding" root="true" />
      <article name="Call Methods" sort="10 Call Methods" id="Getting Started/Widget Basics - Knockout/Call Methods" file="c:\content\00 Getting Started\25 Widget Basics - Knockout\10 Call Methods.md" tags="basics,knockout,call methods,widget instance" root="true" />
      <article name="Handle Events" sort="15 Handle Events" id="Getting Started/Widget Basics - Knockout/Handle Events" file="c:\content\00 Getting Started\25 Widget Basics - Knockout\15 Handle Events.md" tags="basics,knockout,handle events,subscribe" root="true" />
      <article name="Destroy a Widget" sort="20 Destroy a Widget" id="Getting Started/Widget Basics - Knockout/Destroy a Widget" file="c:\content\00 Getting Started\25 Widget Basics - Knockout\20 Destroy a Widget.md" root="true" />
    </article>
    <article name="TypeScript Support" sort="40 TypeScript Support" id="Getting Started/TypeScript Support">
      <article name="Reference TypeScript Definitions" sort="01 Reference TypeScript Definitions" id="Getting Started/TypeScript Support/Reference TypeScript Definitions" file="c:\content\00 Getting Started\40 TypeScript Support\01 Reference TypeScript Definitions.md" tags="typescript support,typescript definitions" root="true" />
      <article name="Configure a Widget" sort="05 Configure a Widget" id="Getting Started/TypeScript Support/Configure a Widget" file="c:\content\00 Getting Started\40 TypeScript Support\05 Configure a Widget.md" tags="typescript support,configure,initialize,type definitions,namespaces" root="true" />
      <article name="Access a Widget" sort="10 Access a Widget" id="Getting Started/TypeScript Support/Access a Widget" file="c:\content\00 Getting Started\40 TypeScript Support\10 Access a Widget.md" tags="typescript support,access a widget,change options,call methods,handle events" root="true" />
    </article>
    <article name="DevExtreme CLI" sort="50 DevExtreme CLI" id="Getting Started/DevExtreme CLI" file="c:\content\00 Getting Started\50 DevExtreme CLI\00 DevExtreme CLI.md" root="true">
      <article name="Installation" sort="01 Installation" id="Getting Started/DevExtreme CLI/Installation" file="c:\content\00 Getting Started\50 DevExtreme CLI\01 Installation.md" />
      <article name="Add DevExtreme to an Existing Application" sort="10 Add DevExtreme to an Existing Application" id="Getting Started/DevExtreme CLI/Add DevExtreme to an Existing Application" file="c:\content\00 Getting Started\50 DevExtreme CLI\10 Add DevExtreme to an Existing Application.md" />
      <article name="DevExtreme Application" sort="20 DevExtreme Application" id="Getting Started/DevExtreme CLI/DevExtreme Application" file="c:\content\00 Getting Started\50 DevExtreme CLI\20 DevExtreme Application\DevExtreme Application.md">
        <article name="Create a New Application" sort="10 Create a New Application" id="Getting Started/DevExtreme CLI/DevExtreme Application/Create a New Application" file="c:\content\00 Getting Started\50 DevExtreme CLI\20 DevExtreme Application\10 Create a New Application.md" />
        <article name="Add the DevExtreme Layout to an Existing Application" sort="20 Add the DevExtreme Layout to an Existing Application" id="Getting Started/DevExtreme CLI/DevExtreme Application/Add the DevExtreme Layout to an Existing Application" file="c:\content\00 Getting Started\50 DevExtreme CLI\20 DevExtreme Application\20 Add the DevExtreme Layout to an Existing Application.md" />
        <article name="Add a View to the Application" sort="30 Add a View to the Application" id="Getting Started/DevExtreme CLI/DevExtreme Application/Add a View to the Application" file="c:\content\00 Getting Started\50 DevExtreme CLI\20 DevExtreme Application\30 Add a View to the Application.md" />
      </article>
      <article name="ThemeBuilder" sort="50 ThemeBuilder" id="Getting Started/DevExtreme CLI/ThemeBuilder" file="c:\content\00 Getting Started\50 DevExtreme CLI\50 ThemeBuilder\00 ThemeBuilder.md">
        <article name="Build a Custom Color Scheme" sort="05 Build a Custom Color Scheme" id="Getting Started/DevExtreme CLI/ThemeBuilder/Build a Custom Color Scheme" file="c:\content\00 Getting Started\50 DevExtreme CLI\50 ThemeBuilder\05 Build a Custom Color Scheme.md" />
        <article name="Export Theme Variables" sort="07 Export Theme Variables" id="Getting Started/DevExtreme CLI/ThemeBuilder/Export Theme Variables" file="c:\content\00 Getting Started\50 DevExtreme CLI\50 ThemeBuilder\07 Export Theme Variables.md" />
        <article name="Export Theme Metadata" sort="08 Export Theme Metadata" id="Getting Started/DevExtreme CLI/ThemeBuilder/Export Theme Metadata" file="c:\content\00 Getting Started\50 DevExtreme CLI\50 ThemeBuilder\08 Export Theme Metadata.md" />
        <article name="Command-Line Arguments" sort="10 Command-Line Arguments" id="Getting Started/DevExtreme CLI/ThemeBuilder/Command-Line Arguments" file="c:\content\00 Getting Started\50 DevExtreme CLI\50 ThemeBuilder\10 Command-Line Arguments.md" />
        <article name="Examples" sort="20 Examples" id="Getting Started/DevExtreme CLI/ThemeBuilder/Examples" file="c:\content\00 Getting Started\50 DevExtreme CLI\50 ThemeBuilder\20 Examples.md" />
      </article>
    </article>
  </article>
  <article name="Widgets" sort="05 Widgets" id="Widgets" file="c:\content\05 Widgets\05 Widgets.md" root="true">
    <article name="Accordion" sort="Accordion" id="Widgets/Accordion">
      <article name="Overview" sort="00 Overview" id="Widgets/Accordion/Overview" file="c:\content\05 Widgets\Accordion\00 Overview.md" tags="dxaccordion,accordion,collection container,collection widget,overview" root="true" />
      <article name="Customize Item Appearance" sort="05 Customize Item Appearance" id="Widgets/Accordion/Customize Item Appearance" file="c:\content\05 Widgets\Accordion\05 Customize Item Appearance.md" tags="accordion,item appearance,customize,templates" root="true" />
      <article name="Control the Behavior" sort="10 Control the Behavior" id="Widgets/Accordion/Control the Behavior" file="c:\content\05 Widgets\Accordion\10 Control the Behavior.md" tags="accordion,behavior,collapse,expand,multiple" root="true" />
      <article name="Keyboard Support" sort="15 Keyboard Support" id="Widgets/Accordion/Keyboard Support" file="c:\content\05 Widgets\Accordion\15 Keyboard Support.md" tags="accordion,accessibility,keyboard shortcuts" root="true" />
    </article>
    <article name="ActionSheet" sort="ActionSheet" id="Widgets/ActionSheet">
      <article name="Overview" sort="00 Overview" id="Widgets/ActionSheet/Overview" file="c:\content\05 Widgets\ActionSheet\00 Overview.md" tags="dxactionsheet,action sheet,actionSheet,collection container,collection widget,navigation,overview" root="true" />
      <article name="Customize Item Appearance" sort="05 Customize Item Appearance" id="Widgets/ActionSheet/Customize Item Appearance" file="c:\content\05 Widgets\ActionSheet\05 Customize Item Appearance.md" tags="action sheet,actionSheet,item appearance,customize,templates,template" root="true" />
      <article name="Specify Display Mode" sort="10 Specify Display Mode" id="Widgets/ActionSheet/Specify Display Mode" file="c:\content\05 Widgets\ActionSheet\10 Specify Display Mode.md" tags="action sheet,actionSheet,display mode,target element" root="true" />
    </article>
    <article name="Autocomplete" sort="Autocomplete" id="Widgets/Autocomplete">
      <article name="Overview" sort="00 Overview" id="Widgets/Autocomplete/Overview" file="c:\content\05 Widgets\Autocomplete\00 Overview.md" tags="dxautocomplete,autocomplete,collection container,collection widget,editor,overview,data source" root="true" />
      <article name="Customize Item Appearance" sort="05 Customize Item Appearance" id="Widgets/Autocomplete/Customize Item Appearance" file="c:\content\05 Widgets\Autocomplete\05 Customize Item Appearance.md" tags="autocomplete,item appearance,customize,templates,template" root="true" />
      <article name="Configure Search Parameters" sort="10 Configure Search Parameters" id="Widgets/Autocomplete/Configure Search Parameters" file="c:\content\05 Widgets\Autocomplete\10 Configure Search Parameters.md" tags="autocomplete,search,search mode,time interval,min search length" root="true" />
    </article>
    <article name="BarGauge" sort="BarGauge" id="Widgets/BarGauge">
      <article name="Visual Elements" sort="10 Visual Elements" id="Widgets/BarGauge/Visual Elements" file="c:\content\05 Widgets\BarGauge\10 Visual Elements\Visual Elements.md" root="true">
        <article name="Bars" sort="20 Bars" id="Widgets/BarGauge/Visual Elements/Bars" file="c:\content\05 Widgets\BarGauge\10 Visual Elements\20 Bars.md" />
        <article name="Labels" sort="30 Labels" id="Widgets/BarGauge/Visual Elements/Labels" file="c:\content\05 Widgets\BarGauge\10 Visual Elements\30 Labels.md" />
        <article name="Tooltips" sort="40 Tooltips" id="Widgets/BarGauge/Visual Elements/Tooltips" file="c:\content\05 Widgets\BarGauge\10 Visual Elements\40 Tooltips.md" />
        <article name="Title and Subtitle" sort="50 Title and Subtitle" id="Widgets/BarGauge/Visual Elements/Title and Subtitle" file="c:\content\05 Widgets\BarGauge\10 Visual Elements\50 Title and Subtitle.md" />
      </article>
    </article>
    <article name="Box" sort="Box" id="Widgets/Box">
      <article name="Overview" sort="00 Overview" id="Widgets/Box/Overview" file="c:\content\05 Widgets\Box\00 Overview.md" tags="dxbox,box,layout widget,overview,dxItem" root="true" />
      <article name="Specify an Item Size" sort="05 Specify an Item Size" id="Widgets/Box/Specify an Item Size" file="c:\content\05 Widgets\Box\05 Specify an Item Size.md" tags="box,item size,item height,item width,baseSize,ratio" root="true" />
      <article name="Arrange and Align Items" sort="10 Arrange and Align Items" id="Widgets/Box/Arrange and Align Items" file="c:\content\05 Widgets\Box\10 Arrange and Align Items.md" tags="box,arrange items in a column,arrange items in a row,direction,items alignment,align items,crossAlign" root="true" />
      <article name="Nest One Box Into Another" sort="15 Nest One Box Into Another" id="Widgets/Box/Nest One Box Into Another" file="c:\content\05 Widgets\Box\15 Nest One Box Into Another.md" tags="box,nest,nested,nest boxes,nested boxes" root="true" />
    </article>
    <article name="Bullet" sort="Bullet" id="Widgets/Bullet">
      <article name="Visual Elements" sort="10 Visual Elements" id="Widgets/Bullet/Visual Elements" file="c:\content\05 Widgets\Bullet\10 Visual Elements\Visual Elements.md" root="true">
        <article name="Bullet Bar" sort="10 Bullet Bar" id="Widgets/Bullet/Visual Elements/Bullet Bar" file="c:\content\05 Widgets\Bullet\10 Visual Elements\10 Bullet Bar.md" />
        <article name="Target Line" sort="20 Target Line" id="Widgets/Bullet/Visual Elements/Target Line" file="c:\content\05 Widgets\Bullet\10 Visual Elements\20 Target Line.md" />
        <article name="Zero Level Line" sort="30 Zero Level Line" id="Widgets/Bullet/Visual Elements/Zero Level Line" file="c:\content\05 Widgets\Bullet\10 Visual Elements\30 Zero Level Line.md" />
        <article name="Tooltip" sort="40 Tooltip" id="Widgets/Bullet/Visual Elements/Tooltip" file="c:\content\05 Widgets\Bullet\10 Visual Elements\40 Tooltip.md" />
      </article>
    </article>
    <article name="Button" sort="Button" id="Widgets/Button">
      <article name="Overview" sort="00 Overview" id="Widgets/Button/Overview" file="c:\content\05 Widgets\Button\00 Overview.md" tags="dxbutton,button,overview,click" root="true" />
      <article name="Customize the Appearance" sort="05 Customize the Appearance" id="Widgets/Button/Customize the Appearance" file="c:\content\05 Widgets\Button\05 Customize the Appearance.md" tags="button,appearance,customize,templates,type,icon" root="true" />
      <article name="Validate and Submit an HTML Form" sort="10 Validate and Submit an HTML Form" id="Widgets/Button/Validate and Submit an HTML Form" file="c:\content\05 Widgets\Button\10 Validate and Submit an HTML Form.md" tags="button,validate a form,submit a form,submit editors" root="true" />
      <article name="Keyboard Support" sort="15 Keyboard Support" id="Widgets/Button/Keyboard Support" file="c:\content\05 Widgets\Button\15 Keyboard Support.md" tags="button,accessibility,keyboard shortcuts" root="true" />
    </article>
    <article name="ButtonGroup" sort="ButtonGroup" id="Widgets/ButtonGroup">
      <article name="Getting Started with ButtonGroup" sort="00 Getting Started with ButtonGroup" id="Widgets/ButtonGroup/Getting Started with ButtonGroup" file="c:\content\05 Widgets\ButtonGroup\00 Getting Started with ButtonGroup\0 Getting Started with ButtonGroup.md" tags="dxbuttongroup" root="true">
        <article name="Create the ButtonGroup" sort="1 Create the ButtonGroup" id="Widgets/ButtonGroup/Getting Started with ButtonGroup/Create the ButtonGroup" file="c:\content\05 Widgets\ButtonGroup\00 Getting Started with ButtonGroup\1 Create the ButtonGroup.md" />
        <article name="Add Buttons to the ButtonGroup" sort="3 Add Buttons to the ButtonGroup" id="Widgets/ButtonGroup/Getting Started with ButtonGroup/Add Buttons to the ButtonGroup" file="c:\content\05 Widgets\ButtonGroup\00 Getting Started with ButtonGroup\3 Add Buttons to the ButtonGroup.md" />
        <article name="Preselect a Button" sort="5 Preselect a Button" id="Widgets/ButtonGroup/Getting Started with ButtonGroup/Preselect a Button" file="c:\content\05 Widgets\ButtonGroup\00 Getting Started with ButtonGroup\5 Preselect a Button.md" />
        <article name="Handle the Selection Change Event" sort="6 Handle the Selection Change Event" id="Widgets/ButtonGroup/Getting Started with ButtonGroup/Handle the Selection Change Event" file="c:\content\05 Widgets\ButtonGroup\00 Getting Started with ButtonGroup\6 Handle the Selection Change Event.md" />
        <article name="Enable Multiple Selection" sort="8 Enable Multiple Selection" id="Widgets/ButtonGroup/Getting Started with ButtonGroup/Enable Multiple Selection" file="c:\content\05 Widgets\ButtonGroup\00 Getting Started with ButtonGroup\8 Enable Multiple Selection.md" />
      </article>
    </article>
    <article name="Calendar" sort="Calendar" id="Widgets/Calendar">
      <article name="Overview" sort="00 Overview" id="Widgets/Calendar/Overview" file="c:\content\05 Widgets\Calendar\00 Overview.md" tags="dxcalendar,calendar,editor,scheduling,overview,value format,date format,date range" root="true" />
      <article name="Handle the Value Change Event" sort="05 Handle the Value Change Event" id="Widgets/Calendar/Handle the Value Change Event" file="c:\content\05 Widgets\Calendar\05 Handle the Value Change Event.md" tags="calendar,editor,get value,set value" root="true" />
      <article name="Specify Zoom Level" sort="10 Specify Zoom Level" id="Widgets/Calendar/Specify Zoom Level" file="c:\content\05 Widgets\Calendar\10 Specify Zoom Level.md" tags="calendar,editor,calendar view,zoomLevel,zoom level" root="true" />
      <article name="Specify the Value Range" sort="12 Specify the Value Range" id="Widgets/Calendar/Specify the Value Range" file="c:\content\05 Widgets\Calendar\12 Specify the Value Range.md" tags="calendar,editor,date range,rande,disable dates,disabledDates" root="true" />
      <article name="Customize Cell Appearance" sort="15 Customize Cell Appearance" id="Widgets/Calendar/Customize Cell Appearance" file="c:\content\05 Widgets\Calendar\15 Customize Cell Appearance.md" tags="calendar,cell appearance,customize,templates" root="true" />
      <article name="Keyboard Support" sort="20 Keyboard Support" id="Widgets/Calendar/Keyboard Support" file="c:\content\05 Widgets\Calendar\20 Keyboard Support.md" tags="calendar,accessibility,keyboard shortcuts" root="true" />
    </article>
    <article name="Chart" sort="Chart" id="Widgets/Chart">
      <article name="Overview" sort="00 Overview" id="Widgets/Chart/Overview" file="c:\content\05 Widgets\Chart\00 Overview.md" tags="dxchart,chart,overview" root="true" />
      <article name="Data Binding" sort="03 Data Binding" id="Widgets/Chart/Data Binding">
        <article name="Simple Array" sort="05 Simple Array" id="Widgets/Chart/Data Binding/Simple Array">
          <article name="Array Only" sort="05 Array Only" id="Widgets/Chart/Data Binding/Simple Array/Array Only" file="c:\content\05 Widgets\Chart\03 Data Binding\05 Simple Array\05 Array Only.md" tags="chart,data binding,provide data,array,process data,Query" root="true" />
          <article name="ArrayStore" sort="10 ArrayStore" id="Widgets/Chart/Data Binding/Simple Array/ArrayStore" file="c:\content\05 Widgets\Chart\03 Data Binding\05 Simple Array\10 ArrayStore.md" tags="chart,data binding,provide data,ArrayStore,DataSource,pagination" root="true" />
        </article>
        <article name="JSON Data" sort="10 JSON Data" id="Widgets/Chart/Data Binding/JSON Data" file="c:\content\05 Widgets\Chart\03 Data Binding\10 JSON Data.md" tags="chart,data binding,provide data,json,jsonp" root="true" />
        <article name="OData Service" sort="15 OData Service" id="Widgets/Chart/Data Binding/OData Service" file="c:\content\05 Widgets\Chart\03 Data Binding\15 OData Service.md" tags="chart,data binding,provide data,odata,ODataStore,DataSource,process data" root="true" />
        <article name="Web API Service" sort="16 Web API Service" id="Widgets/Chart/Data Binding/Web API Service" file="c:\content\05 Widgets\Chart\03 Data Binding\16 Web API Service.md" root="true" />
        <article name="PHP Service" sort="17 PHP Service" id="Widgets/Chart/Data Binding/PHP Service" file="c:\content\05 Widgets\Chart\03 Data Binding\17 PHP Service.md" root="true" />
        <article name="MongoDB Service" sort="18 MongoDB Service" id="Widgets/Chart/Data Binding/MongoDB Service" file="c:\content\05 Widgets\Chart\03 Data Binding\18 MongoDB Service.md" root="true" />
        <article name="Custom Sources" sort="20 Custom Sources" id="Widgets/Chart/Data Binding/Custom Sources" file="c:\content\05 Widgets\Chart\03 Data Binding\20 Custom Sources.md" tags="chart,data binding,provide data,custom data source,CustomStore,DataSource,load" root="true" />
        <article name="Bind Series to Data" sort="23 Bind Series to Data" id="Widgets/Chart/Data Binding/Bind Series to Data" file="c:\content\05 Widgets\Chart\03 Data Binding\23 Bind Series to Data\Bind Series to Data.md" tags="chart,line,bar,area,financial series,range,bubble,argumentField,valueField,series template" root="true">
          <article name="Directly" sort="05 Directly" id="Widgets/Chart/Data Binding/Bind Series to Data/Directly" file="c:\content\05 Widgets\Chart\03 Data Binding\23 Bind Series to Data\05 Directly.md" />
          <article name="Using a Series Template" sort="10 Using a Series Template" id="Widgets/Chart/Data Binding/Bind Series to Data/Using a Series Template" file="c:\content\05 Widgets\Chart\03 Data Binding\23 Bind Series to Data\10 Using a Series Template.md" />
        </article>
        <article name="Update Data" sort="26 Update Data" id="Widgets/Chart/Data Binding/Update Data" file="c:\content\05 Widgets\Chart\03 Data Binding\26 Update Data\Update Data.md" tags="chart,update data,reload data,getDataSource,two-way binding,bindingOptions,observableArray" root="true">
          <article name="DevExtreme DataSource" sort="01 DevExtreme DataSource" id="Widgets/Chart/Data Binding/Update Data/DevExtreme DataSource" file="c:\content\05 Widgets\Chart\03 Data Binding\26 Update Data\01 DevExtreme DataSource.md" />
          <article name="JavaScript Array" sort="05 JavaScript Array" id="Widgets/Chart/Data Binding/Update Data/JavaScript Array" file="c:\content\05 Widgets\Chart\03 Data Binding\26 Update Data\05 JavaScript Array\JavaScript Array.md">
            <article name="jQuery" sort="05 jQuery" id="Widgets/Chart/Data Binding/Update Data/JavaScript Array/jQuery" file="c:\content\05 Widgets\Chart\03 Data Binding\26 Update Data\05 JavaScript Array\05 jQuery.md" />
            <article name="Angular" sort="07 Angular" id="Widgets/Chart/Data Binding/Update Data/JavaScript Array/Angular" file="c:\content\05 Widgets\Chart\03 Data Binding\26 Update Data\05 JavaScript Array\07 Angular.md" />
            <article name="AngularJS" sort="10 AngularJS" id="Widgets/Chart/Data Binding/Update Data/JavaScript Array/AngularJS" file="c:\content\05 Widgets\Chart\03 Data Binding\26 Update Data\05 JavaScript Array\10 AngularJS.md" />
            <article name="Knockout" sort="20 Knockout" id="Widgets/Chart/Data Binding/Update Data/JavaScript Array/Knockout" file="c:\content\05 Widgets\Chart\03 Data Binding\26 Update Data\05 JavaScript Array\20 Knockout.md" />
          </article>
        </article>
      </article>
      <article name="Series" sort="10 Series" id="Widgets/Chart/Series">
        <article name="Overview" sort="00 Overview" id="Widgets/Chart/Series/Overview" file="c:\content\05 Widgets\Chart\10 Series\00 Overview.md" tags="chart,overview,series type,series name,common series settings,inidividual series settings" root="true" />
        <article name="Hover" sort="10 Hover" id="Widgets/Chart/Series/Hover" file="c:\content\05 Widgets\Chart\10 Series\10 Hover\Hover.md" tags="chart,series,hover,hover mode,hoverMode,hover style,hoverStyle,hover changed,seriesHoverChanged" root="true">
          <article name="User Interaction" sort="05 User Interaction" id="Widgets/Chart/Series/Hover/User Interaction" file="c:\content\05 Widgets\Chart\10 Series\10 Hover\05 User Interaction.md" />
          <article name="API" sort="07 API" id="Widgets/Chart/Series/Hover/API" file="c:\content\05 Widgets\Chart\10 Series\10 Hover\07 API.md" />
          <article name="Events" sort="10 Events" id="Widgets/Chart/Series/Hover/Events" file="c:\content\05 Widgets\Chart\10 Series\10 Hover\10 Events.md" />
        </article>
        <article name="Selection" sort="20 Selection" id="Widgets/Chart/Series/Selection" file="c:\content\05 Widgets\Chart\10 Series\20 Selection\Selection.md" tags="chart,series,selection,selection mode,selectionMode,selection style,selectionStyle,selection changed,seriesSelectionChanged,clear selection,clearSelection" root="true">
          <article name="API" sort="01 API" id="Widgets/Chart/Series/Selection/API" file="c:\content\05 Widgets\Chart\10 Series\20 Selection\01 API.md" />
          <article name="User Interaction" sort="05 User Interaction" id="Widgets/Chart/Series/Selection/User Interaction" file="c:\content\05 Widgets\Chart\10 Series\20 Selection\05 User Interaction.md" />
          <article name="Events" sort="10 Events" id="Widgets/Chart/Series/Selection/Events" file="c:\content\05 Widgets\Chart\10 Series\20 Selection\10 Events.md" />
        </article>
        <article name="Access a Series Using the API" sort="40 Access a Series Using the API" id="Widgets/Chart/Series/Access a Series Using the API" file="c:\content\05 Widgets\Chart\10 Series\40 Access a Series Using the API.md" tags="chart,series,get series,getAllSeries,get series by name,getSeriesByName,get series by index,getSeriesByPos" root="true" />
        <article name="Show and Hide a Series" sort="50 Show and Hide a Series" id="Widgets/Chart/Series/Show and Hide a Series" file="c:\content\05 Widgets\Chart\10 Series\50 Show and Hide a Series.md" tags="chart,series,show series,hide series,series visibility" root="true" />
      </article>